[mypy]
python_version = 3.9
disallow_untyped_defs = True
disallow_incomplete_defs = True

# Ignore Mypy errors about packages with missing type hints.

[mypy-boto.*]
ignore_missing_imports = True

[mypy-gevent.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-pkg_resources.*]
ignore_missing_imports = True

# TODO: add type hints incrementally, then remove these overrides

[mypy-datadog.threadstats.*]
disallow_untyped_defs = False
disallow_incomplete_defs = False

